version: "3"

tasks:
  dev:
    desc: Run development server
    deps: [dev-ui, start-test-server]
  test:
    desc: Run tests
    dir: crates/lynx-core
    cmds:
      - cargo test --features test -- --test-threads 1 --nocapture

  lint:
    desc: Run clippy linter
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  fix:
    desc: Run cargo fix
    cmds:
      - cargo fix --allow-dirty

  setup-ui:
    desc: Setup UI dependencies
    dir: crates/lynx-proxy
    cmds:
      - pnpm install

  dev-ui:
    desc: Run UI in development mode
    dir: crates/lynx-proxy
    cmds:
      - pnpm dev

  dev-mock-ui:
    desc: Run UI in mock development mode
    cmds:
      - cd crates/lynx-proxy
      - pnpm dev:mock

  build-ui:
    desc: Build UI
    cmds:
      - cd crates/lynx-proxy && pnpm build
      - rm -rf crates/lynx-cli/assets
      - cp -r crates/lynx-proxy/dist/ crates/lynx-cli/assets

  build-server:
    desc: Build server
    cmds:
      - cargo build --release

  build:
    desc: Build UI and server
    cmds:
      - task: build-ui
      - task: build-server

  start-test-server:
    desc: Start test server
    dir: crates/lynx-core
    cmds:
      - cargo test --package lynx-core --test start_test_server -- start_test_server --exact --nocapture --ignored

  release-minor:
    desc: Release minor version
    cmds:
      - cargo release minor --execute
      # - task: publish
      - task: generate-change-log
  release-patch:
    desc: Release patch version
    cmds:
      - cargo release patch --execute
      # - task: publish
      - task: generate-change-log
  release-alpha:
    desc: Release alpha version
    cmds:
      - cargo release alpha --execute
      # - task: publish
      - task: generate-change-log

  generate-change-log:
    desc: Generate change log
    cmds:
      - git cliff -o CHANGELOG.md
      - git add .
      - git commit --amend --no-edit
      - git push
      - git push --tags


  publish:
    desc: Publish to crates.io
    cmds:
      - task: build-ui
      - cargo publish --registry crates-io -p lynx-core
      - cargo publish --registry crates-io -p lynx-cli --allow-dirty
